### ISSUE TITLE
invalid tag

### ISSUE THREAD

**Issue by YankeeTube** [anonymous5l/wzexplorer#1]
```go
cp, err := wzexplorer.NewCryptProvider(161, wzexplorer.IvEMS)
if err != nil {
	panic(err)
}

f, err := wzexplorer.NewFile(cp, "Character_000.wz")
if err != nil {
	panic(err)
}
defer f.Close()

log.Println(f.Get("00012016.img"))
```

```bash
<nil> invalid tag
```
img parser is not working can i get help?

**Comment by anonymous5l** [comment]
make sure crypto algo is correct, it depends client region and version. try 'IvEmpty' or 'IvGMS' may solve the problem.

**Comment by YankeeTube** [comment]
> make sure crypto algo is correct, it depends client region and version. try 'IvEmpty' or 'IvGMS' may solve the problem.

tk! Strangely, KMS works on IvEmpty.
I'll close the issue.
